/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// Uncomment the package when trying to test:
package codeChallenge05;


public class Library {

    public static void main(String[] args) {


        LinkedList ll = new LinkedList();

        ll.append(10);
        ll.append(11);
        ll.append(12);
        ll.append(13);
        ll.insertBefore(13, 100);
        ll.insertAfter(10, 40);

        System.out.println(ll.toString());
        System.out.println(ll.includes(2));
        System.out.println(ll.getLength());
        try{
            System.out.println(ll.kthFromEnd(4));
        }catch (Exception e) {
            e.printStackTrace();
        }

    }
}
