/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// Uncomment the package when trying to test:
//package main.java.codeChallenge05;

public class Library {

    public static void main(String[] args) {


        LinkedList ll = new LinkedList();
        ll.insert(1);
        ll.insert(2);
        ll.insert(3);
        ll.insert(4);
        ll.insert(5);

        System.out.println(ll.toString());
        System.out.println(ll.includes(2));
    }
}
